package com.example.ui.theme

import androidx.compose.ui.graphics.Color

val EmeraldPrimary = Color(0xFF0E5B44)
val EmeraldOnPrimary = Color(0xFFFFFFFF)
val EmeraldPrimaryContainer = Color(0xFFC5EEDB)
val EmeraldOnPrimaryContainer = Color(0xFF002115)

val GoldSecondary = Color(0xFFC48E2E)
val GoldOnSecondary = Color(0xFFFFFFFF)
val GoldSecondaryContainer = Color(0xFFFDE8BE)
val GoldOnSecondaryContainer = Color(0xFF281800)

val SageTertiary = Color(0xFF346B55)
val SageOnTertiary = Color(0xFFFFFFFF)
val SageTertiaryContainer = Color(0xFFBCEECE)
val SageOnTertiaryContainer = Color(0xFF002113)

val AcademyBackground = Color(0xFFFAF9F5)
val AcademySurface = Color(0xFFFFFFFF)
val AcademySurfaceVariant = Color(0xFFEBEAE4)
val AcademyOnBackground = Color(0xFF181D1A)
val AcademyOnSurface = Color(0xFF181D1A)
val AcademyOnSurfaceVariant = Color(0xFF454B46)
val AcademyOutline = Color(0xFF777E78)
val AcademyOutlineVariant = Color(0xFFC8CEC8)

val DarkEmeraldPrimary = Color(0xFF7BE5BD)
val DarkEmeraldOnPrimary = Color(0xFF003825)
val DarkEmeraldPrimaryContainer = Color(0xFF005137)
val DarkEmeraldOnPrimaryContainer = Color(0xFF98F7D0)

val DarkGoldSecondary = Color(0xFFE5BD6C)
val DarkGoldOnSecondary = Color(0xFF3F2E00)
val DarkGoldSecondaryContainer = Color(0xFF5B4300)
val DarkGoldOnSecondaryContainer = Color(0xFFFFDF9E)

val DarkAcademyBackground = Color(0xFF101513)
val DarkAcademySurface = Color(0xFF161D1A)
val DarkAcademySurfaceVariant = Color(0xFF232D28)
val DarkAcademyOnBackground = Color(0xFFE0E3DE)
val DarkAcademyOnSurface = Color(0xFFE0E3DE)

// Material 3 Serene Sanctuary Design System Tokens (Generated via Google Stitch MCP)
val M3CanvasBackground = Color(0xFFFAFBF9)
val M3SurfaceWhite = Color(0xFFFFFFFF)
val M3EmeraldPrimary = Color(0xFF0E5B44)
val M3EmeraldDark = Color(0xFF004230)
val M3MintContainer = Color(0xFFE8F8F0)
val M3MintSelected = Color(0xFFC8F0DC)
val M3MintSubtle = Color(0xFFF2F8F4)
val M3SageOutline = Color(0xFFC4D7CE)
val M3SageBorder = Color(0xFFE0E5E2)
val M3CharcoalText = Color(0xFF191C1B)
val M3SlateText = Color(0xFF404944)
val M3MutedText = Color(0xFF707973)

// Redesigned Clean / Bento / Apple-Like Design Specification Tokens
val BrandPrimaryEmerald = Color(0xFF0E5B44)
val BrandDarkEmerald = Color(0xFF09392B)
val BrandMint = Color(0xFFC5EEDB)
val BrandGold = Color(0xFFFFD54F)
val BrandDarkGold = Color(0xFFC89B3C)
val BrandPageBackground = Color(0xFFF7F5EF)
val BrandSurface = Color(0xFFFFFFFF)
val BrandSoftSurface = Color(0xFFF1F2EC)
val BrandSoftGreenSurface = Color(0xFFEAF4EE)
val BrandPrimaryText = Color(0xFF18201D)
val BrandSecondaryText = Color(0xFF68716D)
val BrandMutedText = Color(0xFF8C928E)
val BrandDivider = Color(0xFFE5E5DF)
val BrandSuccess = Color(0xFF2E7D32)
val BrandDanger = Color(0xFFD32F2F)
val BrandLiveRed = Color(0xFFE53935)
val BrandDarkVideo = Color(0xFF0F1513)

